export const guests = [
    {
        name: "Bob",
        email: "bob@gmail.com",
        phone: "(123) 333-3333",
        bio: "bob likes donuts",
        job: "Software Engineer",
    },
    {
        name: "Alice",
        email: "alice@gmail.com",
        phone: "(123) 444-4444",
        bio: "alice loves coding",
        job: "Product Manager",
    },
    {
        name: "Charlie",
        email: "charlie@gmail.com",
        phone: "(123) 555-5555",
        bio: "charlie enjoys music",
        job: "Designer",
    },
    {
        name: "Diana",
        email: "diana@gmail.com",
        phone: "(123) 666-6666",
        bio: "diana is a bookworm",
        job: "Data Analyst",
    },
    {
        name: "Evan",
        email: "evan@gmail.com",
        phone: "(123) 777-7777",
        bio: "evan loves sports",
        job: "DevOps Engineer",
    },
    {
        name: "Fiona",
        email: "fiona@gmail.com",
        phone: "(123) 888-8888",
        bio: "fiona enjoys travel",
        job: "Marketing Manager",
    },
    {
        name: "George",
        email: "george@gmail.com",
        phone: "(123) 999-9999",
        bio: "george loves photography",
        job: "Frontend Developer",
    },
    {
        name: "Hannah",
        email: "hannah@gmail.com",
        phone: "(123) 101-0101",
        bio: "hannah enjoys cooking",
        job: "Backend Developer",
    },
    {
        name: "Isaac",
        email: "isaac@gmail.com",
        phone: "(123) 121-2121",
        bio: "isaac is a gamer",
        job: "QA Engineer",
    },
    {
        name: "Julia",
        email: "julia@gmail.com",
        phone: "(123) 131-3131",
        bio: "julia loves gardening",
        job: "UX Designer",
    },
    {
        name: "Kevin",
        email: "kevin@gmail.com",
        phone: "(123) 141-4141",
        bio: "kevin enjoys hiking",
        job: "Systems Administrator",
    },
    {
        name: "Laura",
        email: "laura@gmail.com",
        phone: "(123) 151-5151",
        bio: "laura loves art",
        job: "Project Manager",
    },
    {
        name: "Michael",
        email: "michael@gmail.com",
        phone: "(123) 161-6161",
        bio: "michael enjoys movies",
        job: "Security Engineer",
    },
]